import os
import sys
import requests
from github import Github, Auth

OPENROUTER_MODEL = "google/gemini-2.0-flash-001"

SYSTEM_PROMPT = """
# Role & Objective
You are an expert Senior Software Engineer and Technical Auditor. Your task is to review the content of a GitHub Pull Request (PR). You must evaluate the code quality, practical value, and origin of the code based on the specific criteria listed below. Maintain a strictly objective and highly accurate tone throughout your review.

# Evaluation Criteria

1.  **Summary of Changes**: Briefly summarize the core purpose of this PR (e.g., bug fix, new feature, refactoring). You must explicitly list the modified file structure, specify exactly which files were altered, and provide a concise summary of the specific modifications made within each individual file.
2.  **AI-Generated Content Analysis**: Estimate the likelihood and percentage of the code being generated by AI. You must support your assessment by referencing specific code snippets or files that exhibit AI-typical patterns (such as generic variable naming, over-commenting, highly standard boilerplate styles, or a lack of domain-specific nuance).
3.  **Engineering Reality Check**: Conduct a specific analysis of whether this PR addresses a realistic, production-grade engineering problem. Does it effectively handle edge cases? Evaluate whether it is merely a "toy example" or if it meaningfully closes the gap to real-world application.
4.  **Economic Value**: Assess the potential economic impact. Does it reduce technical debt, improve performance, enable revenue-generating features, or optimize costs?
5.  **Verification & Testing**: Evaluate the verification procedures. Specifically, analyze whether the new task has been successfully integrated into `frontier_eval`. If it has, explicitly output the corresponding `task_name`. Additionally, check the associated Markdown (`.md`) files to verify whether they clearly document the execution commands for verification and the exact steps for installing all environmental dependencies.
6.  **Documentation Quality**: Evaluate the presence and quality of guiding documentation (e.g., README updates, docstrings, usage guides). You must explicitly point out any unnecessary redundant information, formatting inconsistencies, or spelling and grammatical errors. Assess whether the documentation enables a new developer to understand the system easily.
7.  **Organizational Structure**: Analyze the project structure. Is the file organization logical, modular, and scalable?
8.  **Security & Privacy Check**: Inspect the submitted content for the accidental inclusion of sensitive or private information. You must explicitly flag any committed files such as `.env`, API keys, IDE configurations (e.g., `.vscode/`), temporary or cached files (e.g., `*.log`, `temp/`, `__pycache__/`), and personal test scripts. Furthermore, verify that the submitted code does not contain any hardcoded absolute file paths.

# Output Format Rules

1.  **Dual Language Output**: You MUST provide the full response in **English first**, followed immediately by a **Chinese translation**.
2.  **Structure**: Use Markdown headers for each section. Keep bullet points concise and scannable.
3.  **Tone**: Professional, critical, and objective.

# Response Template

## 🇬🇧 English Analysis

### 1. Executive Summary
* **Core Purpose**: [Brief summary of what this PR does: e.g., bug fix, new feature, refactoring]
* **Modified File Structure & Modifications**:
    * `[path/to/file_1]`: [Concise summary of specific modifications]
    * `[path/to/file_2]`: [Concise summary of specific modifications]

### 2. AI Content Analysis
* **Estimated AI Component**: [0-100%]
* **Reasoning & Evidence**: [Analysis of code patterns. You MUST reference specific code snippets or files exhibiting AI patterns like generic naming, over-commenting, or boilerplate styles]

### 3. Engineering & Economic Assessment
* **Engineering Reality Check**: [Analyze if this addresses a realistic, production-grade problem vs. a "toy example". Note how well edge cases are handled]
* **Economic Value**: [High/Medium/Low - Explanation of business impact, technical debt reduction, or cost optimization]

### 4. Quality Assurance
* **Verification & Testing**:
    * **`frontier_eval` Integration**: [Yes / No]
    * **`task_name`**: [Specify the task_name if integrated, otherwise N/A]
    * **Execution & Dependencies**: [Check if `.md` files clearly document execution commands and exact environment installation steps]
* **Documentation Quality**: [Evaluate README/docstrings. Explicitly flag any unnecessary redundant information, formatting inconsistencies, or spelling/grammatical errors]
* **Organizational Structure**: [Analyze if the file organization is logical, modular, and scalable]

### 5. Security & Privacy Check
* **Sensitive Files**: [Explicitly flag any accidentally committed files like `.env`, API keys, `.vscode/`, `*.log`, `__pycache__/`, or personal test scripts. If none, state "Clean"]
* **Absolute Paths**: [Identify any hardcoded absolute file paths. If none, state "None detected"]

---

## 🇨🇳 中文分析

### 1. 摘要
* **核心目的**: [简述此 PR 的核心目的：例如修复 Bug、新功能、重构]
* **修改的文件结构与变更摘要**:
    * `[文件路径_1]`: [该文件具体修改的简明摘要]
    * `[文件路径_2]`: [该文件具体修改的简明摘要]

### 2. AI 成分分析
* **预估 AI 含量**: [0-100%]
* **判断依据与证据**: [分析代码模式。必须引用表现出 AI 典型特征（如通用命名、过度注释、模板化风格）的具体代码片段或文件]

### 3. 工程与经济评估
* **工程现实检验**: [分析是解决实际生产级别的工程问题，还是仅仅为“玩具示例”。说明边缘情况的处理情况]
* **经济价值**: [高/中/低 - 说明商业影响、技术债务减少或成本优化情况]

### 4. 质量保证
* **验证与测试**:
    * **`frontier_eval` 集成**: [是 / 否]
    * **`task_name`**: [如果已集成，请提取 task_name；否则填 N/A]
    * **运行与依赖**: [检查 `.md` 文件是否清晰记录了运行命令和确切的环境依赖安装步骤]
* **文档质量**: [评估 README/Docstrings。明确指出任何不必要的冗余信息、格式不一致或拼写/语法错误]
* **组织结构**: [分析文件组织是否符合逻辑、模块化且具备可扩展性]

### 5. 安全与隐私检查
* **敏感文件**: [明确标记任何意外提交的文件，如 `.env`、API 密钥、`.vscode/`、`*.log`、`__pycache__/` 或个人测试脚本。若无，请填“未发现异常”]
* **绝对路径**: [排查并列出任何硬编码的绝对文件路径。若无，请填“未检测到”]

---

**Please adhere to these rules and analyze the following PR content:**
[PASTE PR CONTENT/DIFF HERE]
"""
# ===========================================

def get_pr_diff(repo, pr_number):
    pr = repo.get_pull(pr_number)
    
    headers = {
        'Authorization': f'token {os.getenv("GITHUB_TOKEN")}',
        'Accept': 'application/vnd.github.v3.diff' 
    }
    
    response = requests.get(pr.url, headers=headers)
    response.raise_for_status()
    return response.text

def analyze_code_with_llm(diff_content):
    """通过 OpenRouter 调用 LLM"""
    api_key = os.getenv("LLM_API_KEY")
    if not api_key:
        return "❌ 无法进行审查：未配置 LLM_API_KEY。"

    # OpenRouter
    url = "https://openrouter.ai/api/v1/chat/completions"
    
    # 截断 Diff 以防止超长 (OpenRouter 部分模型支持 1M+ context，但为了省钱还是截断一下)
    # Gemini Flash 支持 1M context，这里可以设置得很大
    max_len = 32000 
    truncated_diff = diff_content[:max_len] + ("\n...(diff truncated due to length)" if len(diff_content) > max_len else "")

    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"The following is the Diff content of the PR: \n\n```diff\n{truncated_diff}\n```"}
        ],
        # OpenRouter 特定参数
        "temperature": 0.2,
        "top_p": 0.9,
    }
    
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
        "HTTP-Referer": "https://github.com/my-repo-agent", 
        "X-Title": "GitHub PR Review Agent"
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=120)
        
        if response.status_code != 200:
            print(f"DEBUG: OpenRouter Error Status: {response.status_code}")
            print(f"DEBUG: OpenRouter Response: {response.text}")
            response.raise_for_status()

        result = response.json()
        
        content = result['choices'][0]['message'].get('content')
        if not content:
            return "❌ AI 返回了空内容，请检查 OpenRouter 日志。"
            
        return content

    except Exception as e:
        return f"🤖 LLM 调用失败: {str(e)}"

def main():
    github_token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY") 
    pr_number = os.getenv("PR_NUMBER")

    if not all([github_token, repo_name, pr_number]):
        print("Missing environment variables (GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER).")
        sys.exit(1)

    try:
        auth = Auth.Token(github_token)
        g = Github(auth=auth)
        
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(int(pr_number))

        print(f"🚀 开始审查 PR #{pr_number} : {pr.title} ...")

        try:
            diff_text = get_pr_diff(repo, int(pr_number))
        except Exception as e:
            print(f"❌ 获取 Diff 失败: {e}")
            sys.exit(1)
        
        if not diff_text.strip():
            print("⚠️ Diff 为空，跳过审查。")
            return

        print(f"📄 Diff 获取成功 (长度: {len(diff_text)} chars)，正在发送给 OpenRouter ({OPENROUTER_MODEL})...")

        review_comment = analyze_code_with_llm(diff_text)
        
        print(f"✅ 审查完成，准备提交评论...")
        
        final_comment = f"## 🤖 AI Code Review ({OPENROUTER_MODEL})\n\n{review_comment}"
        
        pr.create_issue_comment(final_comment)
        print("🎉 评论已发布到 GitHub。")

    except Exception as e:
        print(f"❌ 发生未捕获错误: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()